# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mathison Clore
email: mathisonclore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mathison Clore recently graduated from Georgetown's School of Foreign Service. He is currently an Associate Consultant at Bain & Company.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mathisonclore.com" # the base hostname & protocol for your site
twitter_username: mathison_clore
github_username:  mathisonclore
linkedin_username:  mathisonclore

# Build settings
markdown: kramdown
